Secure credentials
bleibdirtroy/MobilePrism pull request #22
Opened 2022-07-30 16:25 UTC by bleibdirtroy

- [ ] store password
- [ ] store username
- [ ] store photoprism server
- [ ] store token
- [ ] exceptions and tests

2022-08-05 10:45 UTC, johnns-s requested changes

2022-08-11 21:13 UTC, johnns-s commented
Why are the fields Username and Password allowed to be empty. I think all 3 fields should not be allowed to be empty.

2022-08-11 21:16 UTC, bleibdirtroy commented
Because a public photoprism instance does not need username and password.

2022-08-11 21:17 UTC, johnns-s requested changes

2022-08-11 21:17 UTC, johnns-s commented on lib/services/key_value_storage/secure_storage_provider.dart
> +  }
When I try to login by just using a URL the app crashes with an KeyAlreadyExistsInStorage-Exception

2022-08-11 21:17 UTC, johnns-s commented on lib/services/key_value_storage/secure_storage_provider.dart
> +  }
Can not login at all.

2022-08-14 17:15 UTC, johnns-s approved these changes

2022-08-14 17:15 UTC, merged